Tazkarti/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Tazkarti.Models;

namespace Tazkarti.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}
		
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Tazkarti/Controllers/Match/MatchController.cs
using Microsoft.AspNetCore.Mvc;
using Tazkarti.Models.AppUser;

namespace Tazkarti.Controllers.Match
{
    public class MatchController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        public MatchController( IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Matches()
        {
            ApplicationUser user = new ApplicationUser();
            user.UserName = _httpContextAccessor.HttpContext.Request.Cookies["UserName"];
            return View(user);
        }
        public IActionResult AddTournament() {
            ApplicationUser user = new ApplicationUser();
            user.UserName = _httpContextAccessor.HttpContext.Request.Cookies["UserName"];
            return View("~/Views/Match/AddTournament.cshtml",user);
        }
    }
}

Tazkarti/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Tazkarti";
}
<html>
    <head>
        <link href="/new/style.css" rel="stylesheet" />
        <title>@ViewData["Title"]</title>
        
    </head>
    <body>
       
    <div class="next-plan-component">
        <h2>What do you want to enjoy?</h2>
        <p>
            Book whatever is fun for you
        </p>
    </div>
   <div class="ticket-container">
    <div class="ticket-box sports">
        <div class="ticket-icon">
            <img src="/new/sprot-card-icon.svg" alt="Sports Icon">
        </div>
        <a asp-action="Matches" asp-controller="Match">
                <div class="ticket-text">
            <h2>Sports</h2>
            <p>Match Tickets</p>
        </div>
        </a>
    </div>
    <div class="ticket-box entertainment">
        <div class="ticket-icon">
            <img src="/new/otherEvents.svg" alt="Entertainment Icon">
        </div>
        <div class="ticket-text">
            <h2>Entertainment</h2>
            <p>Event Tickets</p>
        </div>
    </div>
    </div>
    <div class="Logandreg">
        <button type="button" class="btn btn-outline-secondary">Log in</button> 
        <span>or</span>
        <button type="button" class="btn btn-success">Register</button> 
    </div>
   
    </body>
</html>